version: 2.1

orbs:
  flutter: circleci/flutter@2.0.1
  android: circleci/android@2.3.0

parameters:
  app_name:
    type: string
    default: "Kannasol"
  package_name:
    type: string
    default: "com.empresa.kannasol"
  app_url:
    type: string
    default: "https://example.com"
  target_platform:
    type: string
    default: "android"
  enable_chatbot:
    type: boolean
    default: false

jobs:
  build_android:
    docker:
      - image: cimg/android:2023.07.1
    resource_class: large
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: "3.19.0"
      - run:
          name: Setup Android SDK
          command: |
            sdkmanager "platforms;android-34"
            sdkmanager "build-tools;34.0.0"
      - run:
          name: Build Android APK
          command: flutter build apk --release
      - run:
          name: Build Android AAB
          command: flutter build appbundle --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/app-release.aab
          destination: app-release.aab

workflows:
  build_and_deploy:
    jobs:
      - build_android